export const initialCategories = [
  { id: 'gaming', name: 'Gaming & Consoles', icon: 'Gamepad2', count: 28, description: 'Next-gen consoles, gaming PCs, VR, & gear' },
  { id: 'electronics', name: 'Electronics', icon: 'Cpu', count: 32, description: 'Cutting-edge gadgets & personal devices' },
  { id: 'fashion', name: 'Fashion & Apparel', icon: 'Shirt', count: 45, description: 'Trendy outfits & lifestyle apparel' },
  { id: 'home', name: 'Home & Living', icon: 'Home', count: 24, description: 'Modern decor, smart home & furniture' },
  { id: 'footwear', name: 'Footwear & Shoes', icon: 'Footprints', count: 20, description: 'Comfortable sneakers, boots & casual shoes' },
  { id: 'accessories', name: 'Accessories & Watches', icon: 'Watch', count: 35, description: 'Luxury timepieces, bags & eyewear' },
];

export const initialProducts = [
  // Original Products
  {
    id: 'prod-1',
    name: 'Aura Wireless Noise-Canceling Headphones',
    category: 'electronics',
    price: 249.99,
    originalPrice: 299.99,
    rating: 4.8,
    reviewsCount: 142,
    stock: 25,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Experience pure audio immersion with state-of-the-art hybrid noise cancellation, 40-hour battery life, and crystal-clear acoustic drivers.',
    features: ['Active Noise Cancellation', '40H Playtime', 'Fast USB-C Charging', 'Multipoint Bluetooth 5.3'],
    brand: 'AuraSound',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-2',
    name: 'Apex Smart Watch Series X',
    category: 'electronics',
    price: 199.99,
    originalPrice: 249.99,
    rating: 4.7,
    reviewsCount: 98,
    stock: 18,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Track your health, workouts, and notifications seamlessly with an Always-On AMOLED Display and 7-day battery life.',
    features: ['AMOLED HD Screen', 'SpO2 & Heart Rate Tracker', '50m Water Resistance', 'GPS Built-in'],
    brand: 'ApexTech',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-3',
    name: 'Minimalist Artisan Leather Backpack',
    category: 'accessories',
    price: 129.50,
    originalPrice: 159.00,
    rating: 4.9,
    reviewsCount: 64,
    stock: 12,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Crafted from full-grain vegetable-tanned leather. Features padded 15-inch laptop compartment and weather-resistant lining.',
    features: ['Full-Grain Genuine Leather', 'Padded 15" Laptop Sleeve', 'YKK Premium Zippers', 'Ergonomic Straps'],
    brand: 'UrbanCraft',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-4',
    name: 'Vortex Mechanical Gaming Keyboard RGB',
    category: 'gaming',
    price: 89.99,
    originalPrice: 119.99,
    rating: 4.6,
    reviewsCount: 210,
    stock: 40,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Hot-swappable tactile switches, per-key RGB backlighting, aircraft-grade aluminum top plate, and detachable braided cable.',
    features: ['Hot-Swappable Switches', 'Per-Key RGB Customization', 'Aluminum Construction', 'N-Key Rollover'],
    brand: 'Vortex',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-5',
    name: 'Velocity Ultra Running Sneakers',
    category: 'footwear',
    price: 139.99,
    originalPrice: 169.99,
    rating: 4.8,
    reviewsCount: 87,
    stock: 30,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Ultra-lightweight mesh upper coupled with high-rebound foam cushioning for maximum performance and stride energy return.',
    features: ['Breathable Prime Knit', 'High Rebound Cushioning', 'Durable Rubber Outsole', 'Reflective Accents'],
    brand: 'Velocity',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-6',
    name: 'Nordic Ceramic Coffee Set with Wood Tray',
    category: 'home',
    price: 49.99,
    originalPrice: 65.00,
    rating: 4.9,
    reviewsCount: 53,
    stock: 15,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Minimalist handmade matte ceramic cups complete with a natural acacia wood serving tray and bamboo spoons.',
    features: ['Handcrafted Ceramic', 'Natural Acacia Wood Tray', 'Microwave Safe', 'Heat Resistant'],
    brand: 'NordicHome',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-7',
    name: 'Urban Tech Water-Resistant Windbreaker Jacket',
    category: 'fashion',
    price: 79.99,
    originalPrice: 99.99,
    rating: 4.5,
    reviewsCount: 41,
    stock: 22,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Sleek modern windbreaker designed for urban mobility with water-repellent shell and hidden storm hood.',
    features: ['DWR Coating', 'Concealable Hood', 'Deep Zip Pockets', 'Lightweight & Packable'],
    brand: 'UrbanWear',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-8',
    name: 'Chronos Classic Chronograph Steel Watch',
    category: 'accessories',
    price: 219.00,
    originalPrice: 279.00,
    rating: 4.9,
    reviewsCount: 115,
    stock: 9,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Timeless chronograph watch featuring sapphire crystal lens, Japanese quartz movement, and 316L stainless steel bracelet.',
    features: ['Sapphire Glass Crystal', '100m Water Resistance', 'Japanese Quartz Movement', 'Stainless Steel Mesh Strap'],
    brand: 'Chronos',
    createdAt: new Date().toISOString()
  },

  // NEW GAMING & CONSOLES CATEGORY
  {
    id: 'prod-g1',
    name: 'PlayStation 5 Console Disc Edition',
    category: 'gaming',
    price: 499.99,
    originalPrice: 549.99,
    rating: 4.9,
    reviewsCount: 420,
    stock: 15,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback, and 4K 120Hz gaming.',
    features: ['Ultra-High Speed 825GB SSD', 'DualSense Haptic Controller', 'Ray Tracing Support', '4K 120Hz Output'],
    brand: 'Sony PlayStation',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-g2',
    name: 'CyberPower Extreme Gaming PC RTX 4080',
    category: 'gaming',
    price: 1899.99,
    originalPrice: 2199.99,
    rating: 4.9,
    reviewsCount: 88,
    stock: 8,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    images: [
      'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Ultimate 4K gaming power powered by Intel Core i9 14th Gen, NVIDIA RTX 4080 16GB, 32GB DDR5 RAM, and 2TB NVMe SSD.',
    features: ['NVIDIA RTX 4080 16GB', 'Intel i9-14900KF', '32GB DDR5 RAM', 'Liquid Cooling Tower'],
    brand: 'CyberPower',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-g3',
    name: 'Meta Quest 3 VR Headset 128GB',
    category: 'gaming',
    price: 499.00,
    originalPrice: 529.00,
    rating: 4.7,
    reviewsCount: 165,
    stock: 20,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Breakthrough mixed reality headset with 4K resolution, 3D Spatial Audio, and Touch Plus haptic controllers.',
    features: ['Mixed Reality Passthrough', '4K Infinite Display', 'Spatial Audio', 'Wireless Hand Tracking'],
    brand: 'Meta',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-g4',
    name: 'Xbox Wireless Controller Pulse Red',
    category: 'gaming',
    price: 64.99,
    originalPrice: 74.99,
    rating: 4.8,
    reviewsCount: 310,
    stock: 45,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Ergonomic controller with textured grip on triggers, hybrid D-pad, button mapping, and Bluetooth pairing for PC & console.',
    features: ['Textured Trigger Grip', 'Hybrid D-Pad', 'AA Battery / Rechargeable', 'Xbox & PC Bluetooth'],
    brand: 'Microsoft Xbox',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-g5',
    name: 'Steam Deck OLED Handheld Gaming Console 512GB',
    category: 'gaming',
    price: 549.00,
    originalPrice: 599.00,
    rating: 4.9,
    reviewsCount: 240,
    stock: 14,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    images: [
      'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80'
    ],
    description: 'Play your PC Steam library anywhere with a stunning 7.4-inch 90Hz HDR OLED display, faster Wi-Fi 6E, and extended battery.',
    features: ['7.4" 90Hz HDR OLED', 'Wi-Fi 6E Superfast', '50Wh Battery (3-12 hrs)', 'Custom AMD APU'],
    brand: 'Valve',
    createdAt: new Date().toISOString()
  },

  // NEW ELECTRONICS PRODUCTS (5 ITEMS)
  {
    id: 'prod-e1',
    name: 'UltraSlim 4K OLED Smart TV 55"',
    category: 'electronics',
    price: 1199.99,
    originalPrice: 1399.99,
    rating: 4.9,
    reviewsCount: 78,
    stock: 10,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800&auto=format&fit=crop&q=80'],
    description: 'Self-lit OLED pixels deliver perfect blacks, intense colors, Dolby Vision IQ, and 120Hz gaming refresh rate.',
    features: ['OLED 4K Display', 'Dolby Atmos & Vision', '120Hz HDMI 2.1', 'webOS Smart Hub'],
    brand: 'LG Vision',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-e2',
    name: 'ProPod Wireless Earbuds with Active ANC',
    category: 'electronics',
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.7,
    reviewsCount: 154,
    stock: 35,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80'],
    description: 'Compact wireless earbuds with adaptive transparency, 3D Spatial Audio, and wireless mag-safe charging case.',
    features: ['Adaptive Active Noise Cancellation', 'MagSafe Wireless Case', 'IPX4 Sweat Resistant', '30H Battery'],
    brand: 'ProPod',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-e3',
    name: 'Thunderbolt 4 Docking Station 12-in-1',
    category: 'electronics',
    price: 179.99,
    originalPrice: 209.99,
    rating: 4.8,
    reviewsCount: 62,
    stock: 18,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80'],
    description: 'Power dual 4K monitors, pass through 96W charging, and connect high-speed SD card readers with a single cable.',
    features: ['Dual 4K Display Output', '96W Power Delivery', '40Gbps Data Transfer', 'SD & MicroSD Slots'],
    brand: 'TechDock',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-e4',
    name: 'Portable Mini HD Projector 1080P',
    category: 'electronics',
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.6,
    reviewsCount: 92,
    stock: 22,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&auto=format&fit=crop&q=80'],
    description: 'Compact home cinema projector supporting 200-inch display, built-in dual speakers, and 5G Wi-Fi screen mirroring.',
    features: ['Native 1080P Resolution', '200" Display Projection', 'Built-in Stereo Speaker', '5G Wi-Fi & Bluetooth'],
    brand: 'CineView',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-e5',
    name: 'Ergonomic Wireless Vertical Mouse',
    category: 'electronics',
    price: 39.99,
    originalPrice: 49.99,
    rating: 4.7,
    reviewsCount: 180,
    stock: 50,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80'],
    description: 'Scientific ergonomic design promotes neutral posture to reduce wrist strain and muscle tension during long working hours.',
    features: ['57° Ergonomic Vertical Angle', 'Silent Click Buttons', 'Multi-Device Pairing', 'Rechargeable Battery'],
    brand: 'ErgoTech',
    createdAt: new Date().toISOString()
  },

  // NEW FASHION PRODUCTS (5 ITEMS)
  {
    id: 'prod-f1',
    name: 'Organic Cotton Heavyweight Oversized Hoodie',
    category: 'fashion',
    price: 68.00,
    originalPrice: 85.00,
    rating: 4.9,
    reviewsCount: 110,
    stock: 28,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80'],
    description: 'Ultra-soft 450GSM organic French terry cotton fleece with dropped shoulders and double-layered hood.',
    features: ['450GSM Organic Cotton', 'Pre-Shrunk Fabric', 'Kangaroo Pocket', 'Relaxed Oversized Fit'],
    brand: 'UrbanCraft',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-f2',
    name: 'Tailored Slim-Fit Stretch Chino Pants',
    category: 'fashion',
    price: 54.50,
    originalPrice: 69.50,
    rating: 4.7,
    reviewsCount: 74,
    stock: 35,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&auto=format&fit=crop&q=80'],
    description: 'Versatile stretch cotton twill pants tailored for smart-casual office wear or evening outings.',
    features: ['Flex Stretch Cotton', 'Wrinkle Resistant', 'Button Closure with Zip Fly', 'Slim Tapered Leg'],
    brand: 'ModernFit',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-f3',
    name: 'Classic Denim Trucker Jacket',
    category: 'fashion',
    price: 89.00,
    originalPrice: 110.00,
    rating: 4.8,
    reviewsCount: 135,
    stock: 20,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80'],
    description: 'Iconic 100% rigid cotton denim jacket featuring button-flap chest pockets and adjustable waist tabs.',
    features: ['100% Rigid Denim Cotton', 'Metal Shank Buttons', 'Dual Welt Hand Pockets', 'Classic Regular Fit'],
    brand: 'HeritageDenim',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-f4',
    name: 'Merino Wool Crewneck Sweater',
    category: 'fashion',
    price: 95.00,
    originalPrice: 120.00,
    rating: 4.9,
    reviewsCount: 65,
    stock: 16,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80'],
    description: 'Fine 100% Extra Fine Merino Wool knitted into a lightweight, thermal temperature-regulating sweater.',
    features: ['100% Extra Fine Merino Wool', 'Breathable & Odor Resistant', 'Ribbed Cuffs & Hem', 'Soft Touch Texture'],
    brand: 'NordicWear',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-f5',
    name: 'Breathable Athletic Workout Shorts',
    category: 'fashion',
    price: 32.00,
    originalPrice: 42.00,
    rating: 4.6,
    reviewsCount: 89,
    stock: 40,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&auto=format&fit=crop&q=80'],
    description: 'Lightweight quick-dry performance shorts with built-in compression liner and zip phone pocket.',
    features: ['Quick-Dry Tech Fabric', 'Built-in Compression Liner', 'Zippered Phone Pocket', 'Drawstring Waistband'],
    brand: 'Velocity',
    createdAt: new Date().toISOString()
  },

  // NEW HOME & LIVING PRODUCTS (5 ITEMS)
  {
    id: 'prod-h1',
    name: 'Smart Air Purifier with HEPA Filter',
    category: 'home',
    price: 149.99,
    originalPrice: 179.99,
    rating: 4.8,
    reviewsCount: 140,
    stock: 18,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80'],
    description: 'Filters 99.97% of airborne dust, pollen, and allergens for rooms up to 500 sq ft with smart app monitor.',
    features: ['H13 True HEPA Filter', 'Real-Time Air Quality Sensor', 'Ultra-Quiet 24dB Sleep Mode', 'Alexa & App Control'],
    brand: 'PureLiving',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-h2',
    name: 'Minimalist LED Touch Desk Lamp',
    category: 'home',
    price: 45.00,
    originalPrice: 59.00,
    rating: 4.7,
    reviewsCount: 82,
    stock: 30,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80'],
    description: 'Eye-caring non-flickering LED lamp with 5 color temperatures, step-less brightness touch slider, and USB charger.',
    features: ['Eye-Caring Non-Flicker LED', '5 Color Lighting Modes', 'Integrated USB Charging Port', 'Flexible Gooseneck Arm'],
    brand: 'LumiDesk',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-h3',
    name: 'Ergonomic Memory Foam Lumbar Pillow',
    category: 'home',
    price: 35.00,
    originalPrice: 45.00,
    rating: 4.8,
    reviewsCount: 95,
    stock: 25,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80'],
    description: 'Contoured high-density memory foam cushion designed to correct sitting posture and relieve lower back pressure.',
    features: ['100% High-Density Memory Foam', '3D Breathable Mesh Cover', 'Adjustable Dual Straps', 'Ergonomic Curve'],
    brand: 'ErgoHome',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-h4',
    name: 'Aromatherapy Essential Oil Diffuser',
    category: 'home',
    price: 29.99,
    originalPrice: 39.99,
    rating: 4.6,
    reviewsCount: 112,
    stock: 35,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop&q=80'],
    description: 'Ultrasonic cool mist humidifier with 7 soothing ambient LED light colors and auto shut-off function.',
    features: ['300ml Water Tank Capacity', '7 Mood LED Colors', 'Auto Waterless Shut-Off', 'Whisper Quiet Operation'],
    brand: 'AromaZen',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-h5',
    name: 'Stainless Steel Thermal Water Flask 32oz',
    category: 'home',
    price: 24.99,
    originalPrice: 32.99,
    rating: 4.9,
    reviewsCount: 230,
    stock: 50,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80'],
    description: 'Double-wall vacuum insulated flask keeps drinks ice-cold for 24 hours or piping-hot for 12 hours.',
    features: ['18/8 Food-Grade Steel', '24H Cold / 12H Hot Insulation', 'Leakproof Straw Lid', 'BPA-Free Powder Coat'],
    brand: 'HydroQuest',
    createdAt: new Date().toISOString()
  },

  // NEW FOOTWEAR PRODUCTS (5 ITEMS)
  {
    id: 'prod-fw1',
    name: 'Retro Leather Low-Top Streetwear Sneakers',
    category: 'footwear',
    price: 119.00,
    originalPrice: 140.00,
    rating: 4.8,
    reviewsCount: 160,
    stock: 22,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&auto=format&fit=crop&q=80'],
    description: 'Classic 80s inspired silhouette crafted with soft full-grain leather, padded collar, and durable cupsole.',
    features: ['Full-Grain Leather Upper', 'Cushioned EVA Midsole', 'Non-Marking Rubber Sole', 'Retro Perforated Toe'],
    brand: 'Velocity',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-fw2',
    name: 'All-Weather Trail Hiking Waterproof Boots',
    category: 'footwear',
    price: 165.00,
    originalPrice: 195.00,
    rating: 4.9,
    reviewsCount: 88,
    stock: 14,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=800&auto=format&fit=crop&q=80'],
    description: 'Rugged waterproof hiking boots engineered with Gore-Tex membrane and Vibram high-traction rubber lug soles.',
    features: ['Waterproof Membrane', 'Vibram High-Grip Outsole', 'Ankle Support Collar', 'Protective Rubber Toe Cap'],
    brand: 'TrailPeak',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-fw3',
    name: 'Breathable Slip-On Canvas Loafers',
    category: 'footwear',
    price: 58.00,
    originalPrice: 72.00,
    rating: 4.6,
    reviewsCount: 70,
    stock: 30,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=800&auto=format&fit=crop&q=80'],
    description: 'Casual summer slip-on shoes with washed canvas fabric, memory foam insoles, and lightweight flexible soles.',
    features: ['Washed Breathable Canvas', 'Memory Foam Insole', 'Easy Slip-On Design', 'Machine Washable'],
    brand: 'UrbanCraft',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-fw4',
    name: 'Lightweight Cushion Marathon Running Shoes',
    category: 'footwear',
    price: 145.00,
    originalPrice: 175.00,
    rating: 4.9,
    reviewsCount: 195,
    stock: 25,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80'],
    description: 'Engineered for long-distance runners featuring carbon-infused spring plate and responsive foam midsole.',
    features: ['Carbon Spring Plate', 'Engineered Air Mesh', 'Energy-Return Foam', 'Reflective Night Bands'],
    brand: 'Velocity',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-fw5',
    name: 'Classic Genuine Leather Chelsea Boots',
    category: 'footwear',
    price: 185.00,
    originalPrice: 220.00,
    rating: 4.8,
    reviewsCount: 104,
    stock: 12,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&auto=format&fit=crop&q=80'],
    description: 'Handcrafted premium leather boots with elastic side gores and Goodyear welted long-lasting construction.',
    features: ['100% Calfskin Leather', 'Goodyear Welt Construction', 'Elastic Elasticized Gores', 'Leather Lined Interior'],
    brand: 'Chronos',
    createdAt: new Date().toISOString()
  },

  // NEW ACCESSORIES & WATCHES PRODUCTS (5 ITEMS)
  {
    id: 'prod-ac1',
    name: 'Polarized Aviator Sunglasses Stainless Frame',
    category: 'accessories',
    price: 75.00,
    originalPrice: 95.00,
    rating: 4.8,
    reviewsCount: 145,
    stock: 28,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80'],
    description: 'Classic teardrop aviator frame with TAC 100% UV400 anti-glare polarized lenses and silicone nose pads.',
    features: ['100% UV400 Protection', 'Polarized Anti-Glare Lenses', 'Stainless Steel Frame', 'Includes Hard Case & Cloth'],
    brand: 'UrbanCraft',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-ac2',
    name: 'Slim RFID Blocking Matte Carbon Wallet',
    category: 'accessories',
    price: 38.00,
    originalPrice: 48.00,
    rating: 4.9,
    reviewsCount: 220,
    stock: 45,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80'],
    description: 'Ultra-thin minimalist metal wallet holding up to 12 cards with integrated spring money clip and RFID shield.',
    features: ['3K Carbon Fiber Weave', 'RFID Theft Shielding', 'Holds 1-12 Cards', 'Built-in Cash Clip'],
    brand: 'ApexTech',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-ac3',
    name: 'Minimalist Quartz Matte Black Mesh Watch',
    category: 'accessories',
    price: 110.00,
    originalPrice: 139.00,
    rating: 4.7,
    reviewsCount: 92,
    stock: 18,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&auto=format&fit=crop&q=80'],
    description: 'Sleek ultra-thin 7mm case with matte black dial, hardened mineral glass, and magnetic stainless mesh strap.',
    features: ['Ultra-Thin 7mm Case', 'Magnetic Mesh Strap', 'Japanese Quartz Movement', '3ATM Water Resistance'],
    brand: 'Chronos',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-ac4',
    name: 'Canvas & Leather Travel Duffel Bag',
    category: 'accessories',
    price: 98.00,
    originalPrice: 125.00,
    rating: 4.9,
    reviewsCount: 80,
    stock: 15,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80'],
    description: 'Heavyweight waxed canvas weekend bag reinforced with genuine leather handles and padded shoulder strap.',
    features: ['Water-Resistant Waxed Canvas', 'Genuine Leather Accents', 'Separate Shoe Compartment', 'TSA Carry-On Approved'],
    brand: 'UrbanCraft',
    createdAt: new Date().toISOString()
  },
  {
    id: 'prod-ac5',
    name: 'Noise-Isolating HD Audio Earplugs',
    category: 'accessories',
    price: 22.00,
    originalPrice: 29.00,
    rating: 4.6,
    reviewsCount: 165,
    stock: 60,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80'],
    description: 'Reusable high-fidelity hearing protection earplugs that preserve audio quality for concerts and focus.',
    features: ['18dB SNR Noise Reduction', 'Hypoallergenic Silicone', '4 Tip Sizes Included', 'Keyring Carry Case'],
    brand: 'AuraSound',
    createdAt: new Date().toISOString()
  }
];

export const sampleUsers = [
  {
    uid: 'admin-123',
    email: 'admin@skymart.com',
    displayName: 'SkyMart Admin',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    role: 'admin',
    createdAt: new Date().toISOString()
  },
  {
    uid: 'user-456',
    email: 'customer@skymart.com',
    displayName: 'Alex Johnson',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    role: 'customer',
    createdAt: new Date().toISOString()
  }
];
